### PR TITLE
update read/write estimate functions to work with new methods and handle

### PR DESCRIPTION
**Pull request by soniamitchell**

### CODE REVIEW

**Comment by richardreeve** [comment]
@soniamitchell Are these tests supposed to be broken or is this a work in progresss still?

**Comment by richardreeve** [comment]
Also the code in here seems to be dependent on `run_scrc_server` being installed still rather than `start_fair_registry`, so maybe it is still WIP?

**Comment by soniamitchell** [comment]
It's a WIP. The tests failed because I pushed edits to a function I haven't finished working on.

**Comment by soniamitchell** [comment]
Yea, I updated my local registry again today and have updated the script names.

**Comment by richardreeve** [comment]
Okay, I've marked it as draft then so it can't be merged (just so I remember if I come back to it).

**Pull request merged**
